export const DIVISION_COLORS: Record<string, string> = {
  marketing: '#F97316',
  sales: '#14B8A6',
  engineering: '#6366F1',
  design: '#EC4899',
  product: '#8B5CF6',
  'project-management': '#8B5CF6',
  testing: '#EAB308',
  support: '#22C55E',
  finance: '#06B6D4',
  'game-development': '#F43F5E',
  'spatial-computing': '#A78BFA',
  specialized: '#64748B',
  'paid-media': '#FB923C',
  academic: '#0EA5E9',
  strategy: '#D97706',
  general: '#94A3B8',
}

export const DIVISION_SPRITE_KEYS: Record<string, string> = {
  marketing: 'creature_0',
  sales: 'creature_1',
  engineering: 'creature_2',
  design: 'creature_3',
  product: 'creature_4',
  testing: 'creature_5',
  support: 'creature_6',
  finance: 'creature_7',
  'game-development': 'creature_0',
  'spatial-computing': 'creature_1',
  specialized: 'creature_2',
  'paid-media': 'creature_3',
  academic: 'creature_4',
  strategy: 'creature_5',
  general: 'creature_6',
}

export const DIVISION_LABELS: Record<string, string> = {
  marketing: 'Marketing',
  sales: 'Sales',
  engineering: 'Engineering',
  design: 'Design',
  product: 'Product',
  'project-management': 'Project Mgmt',
  testing: 'QA & Testing',
  support: 'Support',
  finance: 'Finance',
  'game-development': 'Game Dev',
  'spatial-computing': 'Spatial',
  specialized: 'Specialized',
  'paid-media': 'Paid Media',
  academic: 'Academic',
  strategy: 'Strategy',
  general: 'General',
}
